baseURL = "https://pennydropper.netlify.com/"
title = "Pennydropper - Lightbulb moments in Data Science"

publishDir = "publish"
author = "James Northrop"
canonifyurls = true
relativeurls = true
languagecode = "en_us"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = "@jamesnorthrop"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
sitename = "Pennydropper - Lightbulb moments in Data Science"
author = "James Northrop"

[permalinks]
post = "/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = "https://pennydropper.netlify.com"
weight = 1
[[menu.main]]
name = "GitHub"
url = "https://github.com/PennyDropper"
weight = 2
[[menu.main]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/james-northrop-63651119/"
weight = 3
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/@JimNorthy"
weight = 4
